# Generated by Django 2.2.2 on 2019-06-19 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bokehApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterIn', models.IntegerField(null=True)),
                ('waterOut', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
