# Generated by Django 2.2.2 on 2019-06-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bokehApp', '0002_currentstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstats',
            name='updated_at',
        ),
    ]
