# Generated by Django 2.2.2 on 2019-06-19 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bokehApp', '0003_remove_currentstats_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentstats',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
